### ISSUE TITLE
code blocks not formatted in some cases

### ISSUE THREAD

**Issue by gumaerc** [mitodl/hugo-course-publisher#154] opened 2020-07-16 18:25 UTC
### Steps to Reproduce

Visit a page that has formatted code blocks, such as: courses/18-s997-introduction-to-matlab-programming-fall-2011/sections/the-basics/command-prompt-and-expressions/

### Expected Behavior

Code blocks are rendered in the specified format

### Actual Behavior

They are rendered as plain text, along with the markdown

### Screenshot or Screencast

![Screen Shot 2020-07-16 at 12 30 42 PM](https://user-images.githubusercontent.com/12089658/87708044-1e7d1580-c770-11ea-84bd-cb26e9360b59.png)

**Comment by aliceriot** [comment] 2020-08-11 16:43
I investigated this a little bit and I've figured out what the issue is. Here's my investigation of one particular error and what I think is going on generally.

In order to follow on problematic line hrough one thing and see what's up I took the line above which, currently, is rendered in `hugo-course-publisher` like this:

![Screenshot from 2020-08-11 11-19-19](https://user-images.githubusercontent.com/6207644/89915580-86cee380-dbc4-11ea-9f90-4ad00c812c7d.png)

as an example to investigate. On production OCW (<https://ocw.mit.edu/courses/mathematics/18-s997-introduction-to-matlab-programming-fall-2011/the-basics/command-prompt-and-expressions/>) this is rendered like this:

![Screenshot from 2020-08-11 11-20-18](https://user-images.githubusercontent.com/6207644/89915683-a9f99300-dbc4-11ea-8770-0fd2b8e6f154.png)

this is what is intended I think. If you have ever used MATLAB the `>>` is the command prompt and the next two lines are the response printed by the REPL.

So we should have a multi-line code block in our markdown to render this correctly. What we actually have, currently, is this:

```md
`>> pi
ans =
    3.1416`
```

so we have correctly recovered the line breaks, but we are fencing the code block with single-backticks (\`) instead of triple-backticks (\`\`\`). Indeed, if I manually edit `site/content/courses/18-s997-introduction-to-matlab-programming-fall-2011/sections/the-basics/command-prompt-and-expressions.md` and change the single-backticks to triple-backticks like this:

````md
```
>> pi
ans =
    3.1416
```
````

 then hugo-course-publisher renders it correctly:

![Screenshot from 2020-08-11 11-28-33](https://user-images.githubusercontent.com/6207644/89916632-d8c43900-dbc5-11ea-812b-a9a3c63b8624.png)

So that tells us that we need to wrap these multi-line blocks in triple-backticks to solve our issue.

Where things get tricky though is the source of the issue in the first place. It looks to me like in the original source these multi-line code blocks are not formatted as multi-line code blocks, but instead as basically two one-line code blocks next to each other.

A proper multi-line code block should look something like this:

```html
<pre>
  <code>
    const foo = bar("baz");
    console.log(foo.toArray().map(fooer => fooer.foo().toString()).join("\n next foo: "))
  <code>
</pre>
```

this is what the HTML for these lines looks like (taken from the `master.json` for this course):

```html
<pre>
  <span style=\"font-size: larger;\">
    <code>
      &gt;&gt; <span style=\"color: rgb(0, 0, 255);\">pi</span>\r\n
      <span style=\"color: rgb(0, 0, 255);\">ans</span> =\r\n
          3.1416
    </code>
  </span>
</pre>
```

the problem is the ` <span style=\"font-size: larger;\">`: it looks as if Turndown sees the `<span>` tag and assumes that the content within is single-line content (which is reasonable - `<span>` is not really supposed to be used this way).

I confirmed this by manually editing the `master.json` to remove the offending spam tag and the code block is translated into markdown properly with triple-backticks and so on (in ocw-to-hugo) and is then rendered correctly:

![Screenshot from 2020-08-11 12-42-50](https://user-images.githubusercontent.com/6207644/89924552-31003880-dbd0-11ea-8ac1-43130a588bff.png)

Anyhow, wondering @gumaerc if you have any thoughts on the best way to fix this. Obviously we need to make a change over in ocw-to-hugo - I'm thinking we can strip out any `<span>` tags that are immediate children of `<code>` tags. Looking through the raw HTML for the page in question it seems that all of the ones that are causing problems share this problem, so that will at least fix this issue.

Do you see any issues with doing that, or potential pitfalls?

**Comment by pdpinch** [comment] 2020-08-11 17:03
The OCW source HTML has span tags inside of pre tags? Is that legal HTML? 

> this is what the HTML for these lines looks like (taken from the master.json for this course):
> <pre>
>   <span style=\"font-size: larger;\">
>     <code>
>       &gt;&gt; <span style=\"color: rgb(0, 0, 255);\">pi</span>\r\n
>       <span style=\"color: rgb(0, 0, 255);\">ans</span> =\r\n
>           3.1416
>     </code>
>   </span>
> </pre>

**Comment by aliceriot** [comment] 2020-08-11 17:21
well it's definitely weird...but browsers seem not to have a problem with it

**Comment by gumaerc** [comment] 2020-08-11 19:58
The way to do this would definitely be a turndown rule.  In the options argument for `turndownService.addRule` you can specify a filter function that gets a JSDOM node passed in, and you return a boolean that determines whether or not it should be processed by the rule.  So you would add the rule for `"code"` and filter out results that aren't `span` tags, then in the `replacement` callback you can strip out the `span`.

**Comment by aliceriot** [comment] 2020-08-11 20:31
cool, I'll give adding that to ocw-to-hugo a go then!

**Comment by aliceriot** [comment] 2020-08-17 18:35
this is closed by https://github.com/mitodl/ocw-to-hugo/pull/58

**Closed by aliceriot** 2020-08-17 18:35 UTC
